/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TalkHappeningNow = {
	mode: 'soon' | 'now';
	talk: Talk;
} | null;

export interface Talk {
	talkId: string;
	talk: string;
	description?: string;
	startsAt?: string;
	speaker: {
		name: string;
		company?: string;
		photo?: string;
	};
}
